services:
  - type: web
    name: glasstasks-web
    env: docker
    plan: starter
    dockerCommand: |
      php artisan migrate --force && \
      php artisan config:cache && php artisan route:cache && \
      php artisan serve --host 0.0.0.0 --port 10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        sync: false
      - key: APP_URL
        value: https://glasstasks.onrender.com
      - key: QUEUE_CONNECTION
        value: redis
      - key: BROADCAST_DRIVER
        value: reverb
  - type: worker
    name: glasstasks-horizon
    env: docker
    dockerCommand: php artisan horizon
  - type: worker
    name: glasstasks-reverb
    env: docker
    dockerCommand: php artisan reverb:start --host 0.0.0.0 --port 6001
  - type: cron
    name: glasstasks-scheduler
    env: docker
    schedule: "*/5 * * * *"
    dockerCommand: php artisan schedule:run